# Site settings
title: 理想，终究会实现  
email: nosun@nosun.cn  
description: nothing 
baseurl: "/"
url: "http://nogun.github.io"

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'tag'


# Social account
weibo:    nosun2008@126.com  
github:   nosun  

# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
